# Generated by Django 3.1 on 2022-02-09 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='Pharmacist_price',
        ),
    ]
