# Generated by Django 3.1 on 2022-02-09 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20220210_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='audience_price',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
