# Generated by Django 3.1 on 2022-02-09 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_product_audience_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='audience_price',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
