# Generated by Django 3.1 on 2022-02-12 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_audience_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Pharmacist_price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='audience_price',
            field=models.PositiveIntegerField(),
        ),
    ]
