# Generated by Django 3.1 on 2022-02-22 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_product_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='afterdiscount_price',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
