# Generated by Django 3.1 on 2022-02-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='slideimage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slideimage_name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, max_length=300)),
                ('slideimage_image', models.ImageField(blank=True, upload_to='photos/slideimages')),
            ],
            options={
                'verbose_name': 'slideimage',
                'verbose_name_plural': 'slideimages',
            },
        ),
    ]
